export const LOG_IN_USER = 'LOG_IN_USER'
export const TOGGLE_CURRENT_TAB = 'TOGGLE_CURRENT_TAB'
export const STORE_DATA_FROM_DB = 'STORE_DATA_FROM_DB'
export const TOGGLE_ADD_NEW_GADGET = 'TOGGLE_ADD_NEW_GADGET'
